[plugin]
repository = "https://github.com/wozaiha/VisibilityPlugin.git"
commit = "3f5a10ccc96e5227d2a7706186474734354ef3fe"
owners = ["SheepGoMeh","wozaiha"]
project_path = "Visibility"
changelog = "Vis国服适配."
