[plugin]
repository = "https://github.com/MeowZWR/ChatTwo.git"
commit = "d34a5e2d1ac8e2dec0bdc95912ea2f29386e65f5"
owners = [
    "Infiziert90",
    "lojewalo",
    "MeowZWR"
]
project_path = "ChatTwo"
