[plugin]
# The open-source Git repository that your code is hosted on.
# Must be visible to the external web, but doesn't have to be GitHub.
# If `git clone` accepts it, it will work here, with the caveat that it
# must be accessible (i.e. no `git` or `ssh` URLs, as the agent cannot clone those)
repository = "https://github.com/LittleNightmare/JustBackup.git"
# The commit to check out and build from the repository.
commit = "9956e30807b98bbe389b0b5e01f35afa5b9fdbf2"
# The people authorised to update this manifest (e.g. who can deploy updates). These are GitHub usernames.
owners = [
    "Eternita-S",
    "LittleNightmare"
]
# The changelog for this version. Will be shown in-game, as well on the Goat Place Discord.
changelog = """
-.NET 6 update again and again
-解决路径问题
"""" 
